DATASET:
  IMG_SIZE: 380
  TRAIN_AUGMENTATIONS:
    COMPOSE:
      [
        Resize,
        HorizontalFlip,
        Normalize
      ]
    NORMALIZE_PARAMS: [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]
  TEST_AUGMENTATIONS:
    COMPOSE: [Resize, Normalize]
    NORMALIZE_PARAMS: [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 10
OPTIMIZER:
  OPTIMIZER_METHOD: adam
  BASE_LR: 0.001
  ADAM_BETAS: [0.9, 0.999]
  EPS: 0.00000001
  WEIGHT_DECAY: 0.000001
LOSS:
  LOSS_FUN: Multi_attentional_Deepfake_Detection_loss
  ENSEMBLE_LOSS_WEIGHT: 1
  AUX_LOSS_WEIGHT: 0.5
  AGDA_LOSS_WEIGHT: 1
  MATCH_LOSS_WEIGHT: 0.1
  ALPHA_DECAY: 0.9
  RESUME_OPTIM: False
MODEL:
  MODEL_NAME: MAT
  FIND_UNUSED_PARAMETERS: True
  NET: efficientnet-b4
  NUM_ATTENTIONS: 4
  ATTENTION_LAYER: b5
  FEATURE_LAYER: b2
  MID_DIMS: 256
  DROPOUT_RATE: 0.25
  DROP_FINAL_RATE: 0.5
  RRETRAINED: FALSE
  ALPHA: 0.05
  SIZE: [380, 380]
  MARGIN: 0.2
  INNER_MARGIN: [0.05, 0.1]
  AGDA_CONFIG:
    AGDA_KERNEL_SIZE: 11
    AGDA_DILATION: 2
    AGDA_SIGMA: 7
    AGDA_SCALE_FACTOR: 0.3
    AGDA_THRESHOLD: [0.4, 0.6]
    AGDA_ZOOM: [3, 5]
    AGDA_NOISE_RATE: 0.1
    AGDA_MODE: soft
    AGDA_LOSS_WEIGHT: 1

